
name: Test

on:
  push:
    branches: [ "main" ]    

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      tasks: ${{ steps.set_tasks.outputs.tasks }}

    steps:
      - uses: actions/checkout@v4

      - name: Define matrix
        id: set_tasks
        run : |
          #echo "tasks<<EOF" >> "$GITHUB_ENV"
          #cat tasks.json >> "$GITHUB_ENV"
          #echo "EOF" >> "$GITHUB_ENV"
          tasks=`cat tasks.json`
          tasks="${tasks//'%'/''}"
          tasks="${tasks//$'\n'/''}"
          tasks="${tasks//$'\r'/''}"
          echo "tasks='$tasks'"
          echo "tasks='$tasks'" >> "$GITHUB_OUTPUT"
      - run: echo "${{fromJson(steps.set_tasks.outputs.tasks)}}"

  test:
    runs-on: ubuntu-latest
    needs: prepare

#   strategy:
#      matrix:
#        tasks: ${{ fromJSON(needs.prepare.outputs.tasks) }}

    steps:
      - run: echo "${{fromJson(needs.prepare.outputs.tasks)}}"

#      - name: show matrix
#        run: echo ${{ matrix }}
        


