name: Multiple Homeworks Publishing

on:
  push:
    branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - page-path: '9-JavaScript-browser/2-DOM/hit-game/'
            page-name: 'hit-game'

    steps:              
    - name: Check if page modified
      id: page    
      continue-on-error: true
      run: |  
        regex_page_path=$(echo "${{ matrix.page-path }}" | sed 's/[.\/]/\\&/g')
        echo $regex_page_path 
        echo ${{ matrix.page-path }} | grep $regex_page_path || 
        echo 'page_modified=false' >> $GITHUB_OUTPUT

    - name: check variable
      run: echo ${{ steps.check_page.outputs.page_modified }}



