name: Multiple Homeworks Publishing

on:
  push:
    branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:              
    - name: Check if page modified
      id: page    
      continue-on-error: true
      run: |  
        echo 'test' | grep tet
        echo 'continue': $?



